import * as fs from "fs";
import * as path from "path";

export interface InitOptions {
  repoRoot: string;
  url?: string;
  framework?: string;
}

export interface InitResult {
  framework: string;
  url: string;
  configPath: string;
  gitignoreUpdated: boolean;
}

// Priority order for detection — first dependency match wins.
const DETECT_ORDER: [string, string][] = [
  ["next", "Next.js"],
  ["nuxt", "Nuxt"],
  ["remix", "Remix"],
  ["astro", "Astro"],
  ["sveltekit", "SvelteKit"],
  ["svelte", "Svelte"],
  ["vue", "Vue"],
  ["vite", "Vite"],
  ["react", "React"],
];

export interface FrameworkMeta {
  framework: string;
  version?: string;
}

/** Detect the framework name plus its installed version range. */
export function detectFrameworkMeta(repoRoot: string): FrameworkMeta {
  try {
    const raw = fs.readFileSync(path.join(repoRoot, "package.json"), "utf-8");
    const pkg = JSON.parse(raw) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
    for (const [dep, name] of DETECT_ORDER) {
      if (deps[dep]) return { framework: name, version: deps[dep] };
    }
  } catch {
    // no package.json — fall through to "unknown"
  }
  return { framework: "unknown" };
}

function detectFramework(repoRoot: string): string {
  return detectFrameworkMeta(repoRoot).framework;
}

function defaultPort(framework: string): number {
  if (["Vite", "Svelte", "SvelteKit", "Vue", "Astro"].includes(framework)) return 5173;
  return 3000;
}

function configTemplate(framework: string, url: string): string {
  return `// aztrx.config.ts — generated by \`aztrx init\` (framework: ${framework})
// Docs: https://aztrx.app/docs/config

export default {
  // Dev server Aztrx should attack.
  url: ${JSON.stringify(url)},

  // Repo root for sourcemap → source resolution (defaults to this directory).
  repo: ".",

  // Max interactions per pass.
  maxActions: 100,

  // Deny-by-default network allow-list for fuzz runs — add your API host here.
  allowHosts: [],
};
`;
}

/** `aztrx init` — detect framework + port, scaffold aztrx.config.ts, seed .gitignore. */
export async function initProject(opts: InitOptions): Promise<InitResult> {
  const repoRoot = path.resolve(opts.repoRoot);
  const framework = opts.framework ?? detectFramework(repoRoot);
  const url = opts.url ?? `http://localhost:${defaultPort(framework)}`;

  const configPath = path.join(repoRoot, "aztrx.config.ts");
  fs.writeFileSync(configPath, configTemplate(framework, url), "utf-8");

  const gitignorePath = path.join(repoRoot, ".gitignore");
  const existing = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, "utf-8") : "";
  let gitignoreUpdated = false;
  if (!/(^|\n)\.aztrx\/\s*\n?/.test(existing)) {
    const sep = existing === "" || existing.endsWith("\n") ? "" : "\n";
    fs.appendFileSync(gitignorePath, `${sep}.aztrx/\n`);
    gitignoreUpdated = true;
  }

  return { framework, url, configPath, gitignoreUpdated };
}
